spring:
  application:
    name: boulisa
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    url: ${DB_URL_FLYWAY}
    user: ${DB_USER_FLYWAY}
    password: ${DB_PASSWORD_FLYWAY}
    baseline-on-migrate: true
    baseline-version: 0