CREATE TABLE account
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid     UUID                                     NOT NULL,
    username VARCHAR(255)                             NOT NULL,
    email    VARCHAR(255)                             NOT NULL,
    password VARCHAR(255)                             NOT NULL,
    role     SMALLINT                                 NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

ALTER TABLE account
    ADD CONSTRAINT uc_account_email UNIQUE (email);

ALTER TABLE account
    ADD CONSTRAINT uc_account_username UNIQUE (username);

ALTER TABLE account
    ADD CONSTRAINT uc_account_uuid UNIQUE (uuid);